<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ModelsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('models')->delete();
    $models1 = array(
      array('id' =>1, 'makes_id' =>1, 'code' =>'AUDI100', 'name' =>'100'),
      array('id' =>2, 'makes_id' =>1, 'code' =>'AUDI200', 'name' =>'200'),
      array('id' =>3, 'makes_id' =>1, 'code' =>'4000', 'name' =>'4000'),
      array('id' =>4, 'makes_id' =>1, 'code' =>'5000', 'name' =>'5000'),
      array('id' =>5, 'makes_id' =>1, 'code' =>'80', 'name' =>'80'),
      array('id' =>6, 'makes_id' =>1, 'code' =>'90', 'name' =>'90'),
      array('id' =>7, 'makes_id' =>1, 'code' =>'A3', 'name' =>'A3'),
      array('id' =>8, 'makes_id' =>1, 'code' =>'A4', 'name' =>'A4'),
      array('id' =>9, 'makes_id' =>1, 'code' =>'A5', 'name' =>'A5'),
      array('id' =>10, 'makes_id' =>1, 'code' =>'A6', 'name' =>'A6'),
      array('id' =>11, 'makes_id' =>1, 'code' =>'A7', 'name' =>'A7'),
      array('id' =>12, 'makes_id' =>1, 'code' =>'A8', 'name' =>'A8'),
      array('id' =>13, 'makes_id' =>1, 'code' =>'ALLRDQUA', 'name' =>'allroad'),
      array('id' =>14, 'makes_id' =>1, 'code' =>'AUDICABRI', 'name' =>'Cabriolet'),
      array('id' =>15, 'makes_id' =>1, 'code' =>'AUDICOUPE', 'name' =>'Coupe'),
      array('id' =>16, 'makes_id' =>1, 'code' =>'Q3', 'name' =>'Q3'),
      array('id' =>17, 'makes_id' =>1, 'code' =>'Q5', 'name' =>'Q5'),
      array('id' =>18, 'makes_id' =>1, 'code' =>'Q7', 'name' =>'Q7'),
      array('id' =>19, 'makes_id' =>1, 'code' =>'QUATTR', 'name' =>'Quattro'),
      array('id' =>20, 'makes_id' =>1, 'code' =>'R8', 'name' =>'R8'),
      array('id' =>21, 'makes_id' =>1, 'code' =>'RS4', 'name' =>'RS 4'),
      array('id' =>22, 'makes_id' =>1, 'code' =>'RS5', 'name' =>'RS 5'),
      array('id' =>23, 'makes_id' =>1, 'code' =>'RS6', 'name' =>'RS 6'),
      array('id' =>24, 'makes_id' =>1, 'code' =>'S4', 'name' =>'S4'),
      array('id' =>25, 'makes_id' =>1, 'code' =>'S5', 'name' =>'S5'),
      array('id' =>26, 'makes_id' =>1, 'code' =>'S6', 'name' =>'S6'),
      array('id' =>27, 'makes_id' =>1, 'code' =>'S7', 'name' =>'S7'),
      array('id' =>28, 'makes_id' =>1, 'code' =>'S8', 'name' =>'S8'),
      array('id' =>29, 'makes_id' =>1, 'code' =>'TT', 'name' =>'TT'),
      array('id' =>30, 'makes_id' =>1, 'code' =>'TTRS', 'name' =>'TT RS'),
      array('id' =>31, 'makes_id' =>1, 'code' =>'TTS', 'name' =>'TTS'),
      array('id' =>32, 'makes_id' =>1, 'code' =>'V8', 'name' =>'V8 Quattro'),
      array('id' =>33, 'makes_id' =>1, 'code' =>'AUDOTH', 'name' =>'Other Audi Models'),
      array('id' =>34, 'makes_id' =>2, 'code' =>'ARNAGE', 'name' =>'Arnage'),
      array('id' =>35, 'makes_id' =>2, 'code' =>'AZURE', 'name' =>'Azure'),
      array('id' =>36, 'makes_id' =>2, 'code' =>'BROOKLANDS', 'name' =>'Brooklands'),
      array('id' =>37, 'makes_id' =>2, 'code' =>'BENCONT', 'name' =>'Continental'),
      array('id' =>38, 'makes_id' =>2, 'code' =>'CORNICHE', 'name' =>'Corniche'),
      array('id' =>39, 'makes_id' =>2, 'code' =>'BENEIGHT', 'name' =>'Eight'),
      array('id' =>40, 'makes_id' =>2, 'code' =>'BENMUL', 'name' =>'Mulsanne'),
      array('id' =>41, 'makes_id' =>2, 'code' =>'BENTURBO', 'name' =>'Turbo R'),
      array('id' =>42, 'makes_id' =>2, 'code' =>'UNAVAILBEN', 'name' =>'Other Bentley Models'),
      array('id' =>43, 'makes_id' =>3, 'code' =>'1_SERIES', 'name' =>'1 Series (3)'),
      array('id' =>44, 'makes_id' =>3, 'code' =>'128I', 'name' =>'128i'),
      array('id' =>45, 'makes_id' =>3, 'code' =>'135I', 'name' =>'135i'),
      array('id' =>46, 'makes_id' =>3, 'code' =>'135IS','name' => '135is'),
      array('id' =>47, 'makes_id' =>3, 'code' =>'3_SERIES', 'name' =>'3 Series (29)'),
      array('id' =>48, 'makes_id' =>3, 'code' =>'318I', 'name' =>'318i'),
      array('id' =>49, 'makes_id' =>3, 'code' =>'318IC', 'name' =>'318iC'),
      array('id' =>50, 'makes_id' =>3, 'code' =>'318IS', 'name' =>'318iS'),
      array('id' =>51, 'makes_id' =>3, 'code' =>'318TI', 'name' =>'318ti'),
      array('id' =>52, 'makes_id' =>3, 'code' =>'320I', 'name' =>'320i'),
      array('id' =>53, 'makes_id' =>3, 'code' =>'323CI', 'name' =>'323ci'),
      array('id' =>54, 'makes_id' =>3, 'code' =>'323I', 'name' =>'323i'),
      array('id' =>55, 'makes_id' =>3, 'code' =>'323IS', 'name' =>'323is'),
      array('id' =>56, 'makes_id' =>3, 'code' =>'323IT', 'name' =>'323iT'),
      array('id' =>57, 'makes_id' =>3, 'code' =>'325CI', 'name' =>'325Ci'),
      array('id' =>58, 'makes_id' =>3, 'code' =>'325E', 'name' =>'325e'),
      array('id' =>59, 'makes_id' =>3, 'code' =>'325ES', 'name' =>'325es'),
      array('id' =>60, 'makes_id' =>3, 'code' =>'325I', 'name' =>'325i'),
      array('id' =>61, 'makes_id' =>3, 'code' =>'325IS', 'name' =>'325is'),
      array('id' =>62, 'makes_id' =>3, 'code' =>'325IX', 'name' =>'325iX'),
      array('id' =>63, 'makes_id' =>3, 'code' =>'325XI', 'name' =>'325xi'),
      array('id' =>64, 'makes_id' =>3, 'code' =>'328CI', 'name' =>'328Ci'),
      array('id' =>65, 'makes_id' =>3, 'code' =>'328I', 'name' =>'328i'),
      array('id' =>66, 'makes_id' =>3, 'code' =>'328IS', 'name' =>'328iS'),
      array('id' =>67, 'makes_id' =>3, 'code' =>'328XI', 'name' =>'328xi'),
      array('id' =>68, 'makes_id' =>3, 'code' =>'330CI', 'name' =>'330Ci'),
      array('id' =>69, 'makes_id' =>3, 'code' =>'330I', 'name' =>'330i'),
      array('id' =>70, 'makes_id' =>3, 'code' =>'330XI', 'name' =>'330xi'),
      array('id' =>71, 'makes_id' =>3, 'code' =>'335D', 'name' =>'335d'),
      array('id' =>72, 'makes_id' =>3, 'code' =>'335I', 'name' =>'335i'),
      array('id' =>73, 'makes_id' =>3, 'code' =>'335IS', 'name' =>'335is'),
      array('id' =>74, 'makes_id' =>3, 'code' =>'335XI', 'name' =>'335xi'),
      array('id' =>75, 'makes_id' =>3, 'code' =>'ACTIVE3', 'name' =>'ActiveHybrid 3'),
      array('id' =>76, 'makes_id' =>3, 'code' =>'BMW325', 'name' =>'325'),
      array('id' =>77, 'makes_id' =>3, 'code' =>'5_SERIES', 'name' =>'5 Series (19)'),
      array('id' =>78, 'makes_id' =>3, 'code' =>'524TD', 'name' =>'524td'),
      array('id' =>79, 'makes_id' =>3, 'code' =>'525I', 'name' =>'525i'),
      array('id' =>80, 'makes_id' =>3, 'code' =>'525XI', 'name' =>'525xi'),
      array('id' =>81, 'makes_id' =>3, 'code' =>'528E', 'name' =>'528e'),
      array('id' =>82, 'makes_id' =>3, 'code' =>'528I', 'name' =>'528i'),
      array('id' =>83, 'makes_id' =>3, 'code' =>'528IT', 'name' =>'528iT'),
      array('id' =>84, 'makes_id' =>3, 'code' =>'528XI', 'name' =>'528xi'),
      array('id' =>85, 'makes_id' =>3, 'code' =>'530I', 'name' =>'530i'),
      array('id' =>86, 'makes_id' =>3, 'code' =>'530IT', 'name' =>'530iT'),
      array('id' =>87, 'makes_id' =>3, 'code' =>'530XI', 'name' =>'530xi'),
      array('id' =>88, 'makes_id' =>3, 'code' =>'533I', 'name' =>'533i'),
      array('id' =>89, 'makes_id' =>3, 'code' =>'535I', 'name' =>'535i'),
      array('id' =>90, 'makes_id' =>3, 'code' =>'535IGT', 'name' =>'535i Gran Turismo'),
      array('id' =>91, 'makes_id' =>3, 'code' =>'535XI', 'name' =>'535xi'),
      array('id' =>92, 'makes_id' =>3, 'code' =>'540I', 'name' =>'540i'),
      array('id' =>93, 'makes_id' =>3, 'code' =>'545I', 'name' =>'545i'),
      array('id' =>94, 'makes_id' =>3, 'code' =>'550I', 'name' =>'550i'),
      array('id' =>95, 'makes_id' =>3, 'code' =>'550IGT', 'name' =>'550i Gran Turismo'),
      array('id' =>96, 'makes_id' =>3, 'code' =>'ACTIVE5', 'name' =>'ActiveHybrid 5'),
      array('id' =>97, 'makes_id' =>3, 'code' =>'6_SERIES', 'name' =>'6 Series (8)'),
      array('id' =>98, 'makes_id' =>3, 'code' =>'633CSI', 'name' =>'633CSi'),
      array('id' =>99, 'makes_id' =>3, 'code' =>'635CSI', 'name' =>'635CSi'),
      array('id' =>100, 'makes_id' =>3, 'code' =>'640I', 'name' =>'640i'),
      array('id' =>101, 'makes_id' =>3, 'code' =>'640IGC', 'name' =>'640i Gran Coupe'),
      array('id' =>102, 'makes_id' =>3, 'code' =>'645CI', 'name' =>'645Ci'),
      array('id' =>103, 'makes_id' =>3, 'code' =>'650I', 'name' =>'650i'),
      array('id' =>104, 'makes_id' =>3, 'code' =>'650IGC', 'name' =>'650i Gran Coupe'),
      array('id' =>105, 'makes_id' =>3, 'code' =>'L6', 'name' =>' - L6'),
      array('id' =>106, 'makes_id' =>3, 'code' =>'7_SERIES', 'name' =>'7 Series (15)'),
      array('id' =>107, 'makes_id' =>3, 'code' =>'733I', 'name' =>'733i'),
      array('id' =>108, 'makes_id' =>3, 'code' =>'735I', 'name' =>'735i'),
      array('id' =>109, 'makes_id' =>3, 'code' =>'735IL', 'name' =>'735iL'),
      array('id' =>110, 'makes_id' =>3, 'code' =>'740I', 'name' =>'740i'),
      array('id' =>111, 'makes_id' =>3, 'code' =>'740IL', 'name' =>'740iL'),
      array('id' =>112, 'makes_id' =>3, 'code' =>'740LI', 'name' =>'740Li'),
      array('id' =>113, 'makes_id' =>3, 'code' =>'745I', 'name' =>'745i'),
      array('id' =>114, 'makes_id' =>3, 'code' =>'745LI', 'name' =>'745Li'),
      array('id' =>115, 'makes_id' =>3, 'code' =>'750I', 'name' =>'750i'),
      array('id' =>116, 'makes_id' =>3, 'code' =>'750IL', 'name' =>'750iL'),
      array('id' =>117, 'makes_id' =>3, 'code' =>'750LI', 'name' =>'750Li'),
      array('id' =>118, 'makes_id' =>3, 'code' =>'760I', 'name' =>'760i'),
      array('id' =>119, 'makes_id' =>3, 'code' =>'760LI', 'name' =>'760Li'),
      array('id' =>120, 'makes_id' =>3, 'code' =>'ACTIVE7', 'name' =>'ActiveHybrid 7'),
      array('id' =>121, 'makes_id' =>3, 'code' =>'ALPINAB7', 'name' =>'Alpina B7'),
      array('id' =>122, 'makes_id' =>3, 'code' =>'8_SERIES', 'name' =>'8 Series (4)'),
      array('id' =>123, 'makes_id' =>3, 'code' =>'840CI', 'name' =>'840Ci'),
      array('id' =>124, 'makes_id' =>3, 'code' =>'850CI', 'name' =>'850Ci'),
      array('id' =>125, 'makes_id' =>3, 'code' =>'850CSI', 'name' =>'850CSi'),
      array('id' =>126, 'makes_id' =>3, 'code' =>'850I', 'name' =>' - 850i'),
      array('id' =>127, 'makes_id' =>3, 'code' =>'L_SERIES', 'name' =>'L Series (1)'),
      array('id' =>128, 'makes_id' =>3, 'code' =>'L7', 'name' =>' - L7'),
      array('id' =>129, 'makes_id' =>3, 'code' =>'M_SERIES', 'name' =>'M Series (8)'),
      array('id' =>130, 'makes_id' =>3, 'code' =>'1SERIESM', 'name' =>'1 Series M'),
      array('id' =>131, 'makes_id' =>3, 'code' =>'BMWMCOUPE', 'name' =>'M Coupe'),
      array('id' =>132, 'makes_id' =>3, 'code' =>'BMWROAD', 'name' =>'M Roadster'),
      array('id' =>133, 'makes_id' =>3, 'code' =>'M3', 'name' =>'M3'),
      array('id' =>134, 'makes_id' =>3, 'code' =>'M5', 'name' =>'M5'),
      array('id' =>135, 'makes_id' =>3, 'code' =>'M6', 'name' =>'M6'),
      array('id' =>136, 'makes_id' =>3, 'code' =>'X5M', 'name' =>'X5 M'),
      array('id' =>137, 'makes_id' =>3, 'code' =>'X6M', 'name' =>'X6 M'),
      array('id' =>138, 'makes_id' =>3, 'code' =>'X_SERIES', 'name' =>'X Series (5)'),
      array('id' =>139, 'makes_id' =>3, 'code' =>'ACTIVEX6', 'name' =>'ActiveHybrid X6'),
      array('id' =>140, 'makes_id' =>3, 'code' =>'X1', 'name' =>'X1'),
      array('id' =>141, 'makes_id' =>3, 'code' =>'X3', 'name' =>'X3'),
      array('id' =>142, 'makes_id' =>3, 'code' =>'X5', 'name' =>'X5'),
      array('id' =>143, 'makes_id' =>3, 'code' =>'X6', 'name' =>'X6'),
      array('id' =>144, 'makes_id' =>3, 'code' =>'Z_SERIES', 'name' =>'Z Series (3)'),
      array('id' =>145, 'makes_id' =>3, 'code' =>'Z3', 'name' =>'Z3'),
      array('id' =>146, 'makes_id' =>3, 'code' =>'Z4', 'name' =>'Z4'),
      array('id' =>147, 'makes_id' =>3, 'code' =>'Z8', 'name' =>'Z8'),
      array('id' =>148, 'makes_id' =>3, 'code' =>'BMWOTH', 'name' =>'Other BMW Models'),
      array('id' =>149, 'makes_id' =>4, 'code' =>'ASTRO', 'name' =>'Astro'),
      array('id' =>150, 'makes_id' =>4, 'code' =>'AVALNCH', 'name' =>'Avalanche'),
      array('id' =>151, 'makes_id' =>4, 'code' =>'AVEO', 'name' =>'Aveo'),
      array('id' =>152, 'makes_id' =>4, 'code' =>'AVEO5', 'name' =>'Aveo5'),
      array('id' =>153, 'makes_id' =>4, 'code' =>'BERETT', 'name' =>'Beretta'),
      array('id' =>154, 'makes_id' =>4, 'code' =>'BLAZER', 'name' =>'Blazer'),
      array('id' =>155, 'makes_id' =>4, 'code' =>'CAM', 'name' =>'Camaro'),
      array('id' =>156, 'makes_id' =>4, 'code' =>'CAP', 'name' =>'Caprice'),
      array('id' =>157, 'makes_id' =>4, 'code' =>'CHECAPS', 'name' =>'Captiva Sport'),
      array('id' =>158, 'makes_id' =>4, 'code' =>'CAV', 'name' =>'Cavalier'),
      array('id' =>159, 'makes_id' =>4, 'code' =>'CELE', 'name' =>'Celebrity'),
      array('id' =>160, 'makes_id' =>4, 'code' =>'CHEVETTE', 'name' =>'Chevette'),
      array('id' =>161, 'makes_id' =>4, 'code' =>'CITATION', 'name' =>'Citation'),
      array('id' =>162, 'makes_id' =>4, 'code' =>'COBALT', 'name' =>'Cobalt'),
      array('id' =>163, 'makes_id' =>4, 'code' =>'COLORADO', 'name' =>'Colorado'),
      array('id' =>164, 'makes_id' =>4, 'code' =>'CORSI', 'name' =>'Corsica'),
      array('id' =>165, 'makes_id' =>4, 'code' =>'CORV', 'name' =>'Corvette'),
      array('id' =>166, 'makes_id' =>4, 'code' =>'CRUZE', 'name' =>'Cruze'),
      array('id' =>167, 'makes_id' =>4, 'code' =>'ELCAM', 'name' =>'El Camino'),
      array('id' =>168, 'makes_id' =>4, 'code' =>'EQUINOX', 'name' =>'Equinox'),
      array('id' =>169, 'makes_id' =>4, 'code' =>'G15EXP', 'name' =>'Express Van'),
      array('id' =>170, 'makes_id' =>4, 'code' =>'G10', 'name' =>'G Van'),
      array('id' =>171, 'makes_id' =>4, 'code' =>'HHR', 'name' =>'HHR'),
      array('id' =>172, 'makes_id' =>4, 'code' =>'CHEVIMP', 'name' =>'Impala'),
      array('id' =>173, 'makes_id' =>4, 'code' =>'KODC4500', 'name' =>'Kodiak C4500'),
      array('id' =>174, 'makes_id' =>4, 'code' =>'LUMINA', 'name' =>'Lumina'),
      array('id' =>175, 'makes_id' =>4, 'code' =>'LAPV', 'name' =>'Lumina APV'),
      array('id' =>176, 'makes_id' =>4, 'code' =>'LUV', 'name' =>'LUV'),
      array('id' =>177, 'makes_id' =>4, 'code' =>'MALI', 'name' =>'Malibu'),
      array('id' =>178, 'makes_id' =>4, 'code' =>'CHVMETR', 'name' =>'Metro'),
      array('id' =>179, 'makes_id' =>4, 'code' =>'CHEVMONT', 'name' =>'Monte Carlo'),
      array('id' =>180, 'makes_id' =>4, 'code' =>'NOVA', 'name' =>'Nova'),
      array('id' =>181, 'makes_id' =>4, 'code' =>'CHEVPRIZM', 'name' =>'Prizm'),
      array('id' =>182, 'makes_id' =>4, 'code' =>'CHVST', 'name' =>'S10 Blazer'),
      array('id' =>183, 'makes_id' =>4, 'code' =>'S10PICKUP', 'name' =>'S10 Pickup'),
      array('id' =>184, 'makes_id' =>4, 'code' =>'CHEV150','name' => 'Silverado and other C/K1500'),
      array('id' =>185, 'makes_id' =>4, 'code' =>'CHEVC25', 'name' =>'Silverado and other C/K2500'),
      array('id' =>186, 'makes_id' =>4, 'code' =>'CH3500PU','name' => 'Silverado and other C/K3500'),
      array('id' =>187, 'makes_id' =>4, 'code' =>'SONIC', 'name' =>'Sonic'),
      array('id' =>188, 'makes_id' =>4, 'code' =>'SPARK', 'name' =>'Spark'),
      array('id' =>189, 'makes_id' =>4, 'code' =>'CHEVSPEC','name' =>'Spectrum'),
      array('id' =>190, 'makes_id' =>4, 'code' =>'CHSPRINT', 'name' =>'Sprint'),
      array('id' =>191, 'makes_id' =>4, 'code' =>'SSR', 'name' =>'SSR'),
      array('id' =>192, 'makes_id' =>4, 'code' =>'CHEVSUB', 'name' =>'Suburban'),
      array('id' =>193, 'makes_id' =>4, 'code' =>'TAHOE', 'name' =>'Tahoe'),
      array('id' =>194, 'makes_id' =>4, 'code' =>'TRACKE', 'name' =>'Tracker'),
      array('id' =>195, 'makes_id' =>4, 'code' =>'TRAILBLZ','name' => 'TrailBlazer'),
      array('id' =>196, 'makes_id' =>4, 'code' =>'TRAILBZEXT','name' => 'TrailBlazer EXT'),
      array('id' =>197, 'makes_id' =>4, 'code' =>'TRAVERSE','name' => 'Traverse'),
      array('id' =>198, 'makes_id' =>4, 'code' =>'UPLANDER', 'name' =>'Uplander'),
      array('id' =>199, 'makes_id' =>4, 'code' =>'VENTUR','name' => 'Venture'),
      array('id' =>200, 'makes_id' =>4, 'code' =>'VOLT', 'name' =>'Volt'),
      array('id' =>201, 'makes_id' =>4, 'code' =>'CHEOTH','name' => 'Other Chevrolet Models'),
      array('id' =>202, 'makes_id' =>5, 'code' =>'LANOS', 'name' =>'Lanos'),
      array('id' =>203, 'makes_id' =>5, 'code' =>'LEGANZA', 'name' =>'Leganza'),
      array('id' =>204, 'makes_id' =>5, 'code' =>'NUBIRA', 'name' =>'Nubira'),
      array('id' =>205, 'makes_id' =>5, 'code' =>'DAEOTH', 'name' =>'Other Daewoo Models'),
      array('id' =>206, 'makes_id' =>6, 'code' =>'CHAR', 'name' =>'Charade'),
      array('id' =>207, 'makes_id' =>6, 'code' =>'ROCKY','name' => 'Rocky'),
      array('id' =>208, 'makes_id' =>6, 'code' =>'DAIHOTH','name' => 'Other Daihatsu Models'),
      array('id' =>209, 'makes_id' =>7, 'code' =>'2000', 'name' =>'2000 Spider'),
      array('id' =>210, 'makes_id' =>7, 'code' =>'FIAT500','name' => '500'),
      array('id' =>211, 'makes_id' =>7, 'code' =>'BERTON', 'name' =>'Bertone X1/9'),
      array('id' =>212, 'makes_id' =>7, 'code' =>'BRAVA', 'name' =>'Brava'),
      array('id' =>213, 'makes_id' =>7, 'code' =>'PININ', 'name' =>'Pininfarina Spider'),
      array('id' =>214, 'makes_id' =>7, 'code' =>'STRADA', 'name' =>'Strada'),
      array('id' =>215, 'makes_id' =>7, 'code' =>'FIATX19','name' => 'X1/9'),
      array('id' =>216, 'makes_id' =>7, 'code' =>'UNAVAILFIA', 'name' =>'Other Fiat Models'),
      array('id' =>217, 'makes_id' =>8, 'code' =>'AERO', 'name' =>'Aerostar'),
      array('id' =>218, 'makes_id' =>8, 'code' =>'ASPIRE','name' => 'Aspire'),
      array('id' =>219, 'makes_id' =>8, 'code' =>'BRON','name' => 'Bronco'),
      array('id' =>220, 'makes_id' =>8, 'code' =>'B2', 'name' =>'Bronco II'),
      array('id' =>221, 'makes_id' =>8, 'code' =>'FOCMAX','name' => 'C-MAX'),
      array('id' =>222, 'makes_id' =>8, 'code' =>'FORDCLUB', 'name' =>'Club Wagon'),
      array('id' =>223, 'makes_id' =>8, 'code' =>'CONTOUR', 'name' =>'Contour'),
      array('id' =>224, 'makes_id' =>8, 'code' =>'COURIER','name' => 'Courier'),
      array('id' =>225, 'makes_id' =>8, 'code' =>'CROWNVIC', 'name' =>'Crown Victoria'),
      array('id' =>226, 'makes_id' =>8, 'code' =>'E150ECON','name' => 'E-150 and Econoline 150'),
      array('id' =>227, 'makes_id' =>8, 'code' =>'E250ECON','name' => 'E-250 and Econoline 250'),
      array('id' =>228, 'makes_id' =>8, 'code' =>'E350ECON','name' => 'E-350 and Econoline 350'),
      array('id' =>229, 'makes_id' =>8, 'code' =>'EDGE', 'name' =>'Edge'),
      array('id' =>300, 'makes_id' =>8, 'code' =>'ESCAPE', 'name' =>'Escape'),
      array('id' =>301, 'makes_id' =>8, 'code' =>'ESCO', 'name' =>'Escort'),
      array('id' =>302, 'makes_id' =>8, 'code' =>'EXCURSION', 'name' =>'Excursion'),
      array('id' =>303, 'makes_id' =>8, 'code' =>'EXP', 'name' =>'EXP'),
      array('id' =>304, 'makes_id' =>8, 'code' =>'EXPEDI','name' => 'Expedition'),
      array('id' =>305, 'makes_id' =>8, 'code' =>'EXPEDIEL','name' => 'Expedition EL'),
      array('id' =>306, 'makes_id' =>8, 'code' =>'EXPLOR', 'name' =>'Explorer'),
      array('id' =>307, 'makes_id' =>8, 'code' =>'SPORTTRAC','name' => 'Explorer Sport Trac'),
      array('id' =>308, 'makes_id' =>8, 'code' =>'F100', 'name' =>'F100'),
      array('id' =>309, 'makes_id' =>8, 'code' =>'F150PICKUP', 'name' =>'F150'),
      array('id' =>310, 'makes_id' =>8, 'code' =>'F250', 'name' =>'F250'),
      array('id' =>311, 'makes_id' =>8, 'code' =>'F350', 'name' =>'F350'),
      array('id' =>312, 'makes_id' =>8, 'code' =>'F450', 'name' =>'F450'),
      array('id' =>313, 'makes_id' =>8, 'code' =>'FAIRM', 'name' =>'Fairmont'),
      array('id' =>314, 'makes_id' =>8, 'code' =>'FESTIV','name' => 'Festiva'),
      array('id' =>315, 'makes_id' =>8, 'code' =>'FIESTA', 'name' =>'Fiesta'),
      array('id' =>316, 'makes_id' =>8, 'code' =>'FIVEHUNDRE','name' => 'Five Hundred'),
      array('id' =>317, 'makes_id' =>8, 'code' =>'FLEX','name' => 'Flex'),
      array('id' =>318, 'makes_id' =>8, 'code' =>'FOCUS', 'name' =>'Focus'),
      array('id' =>319, 'makes_id' =>8, 'code' =>'FREESTAR', 'name' =>'Freestar'),
      array('id' =>320, 'makes_id' =>8, 'code' =>'FREESTYLE','name' => 'Freestyle'),
      array('id' =>321, 'makes_id' =>8, 'code' =>'FUSION','name' => 'Fusion'),
      array('id' =>322, 'makes_id' =>8, 'code' =>'GRANADA', 'name' =>'Granada'),
      array('id' =>323, 'makes_id' =>8, 'code' =>'GT','name' => 'GT'),
      array('id' =>324, 'makes_id' =>8, 'code' =>'LTD','name' => 'LTD'),
      array('id' =>325, 'makes_id' =>8, 'code' =>'MUST','name' => 'Mustang'),
      array('id' =>326, 'makes_id' =>8, 'code' =>'PROBE', 'name' =>'Probe'),
      array('id' =>327, 'makes_id' =>8, 'code' =>'RANGER', 'name' =>'Ranger'),
      array('id' =>328, 'makes_id' =>8, 'code' =>'TAURUS', 'name' =>'Taurus'),
      array('id' =>329, 'makes_id' =>8, 'code' =>'TAURUSX','name' => 'Taurus X'),
      array('id' =>330, 'makes_id' =>8, 'code' =>'TEMPO','name' => 'Tempo'),
      array('id' =>482, 'makes_id' =>8, 'code' =>'TBIRD','name' => 'Thunderbird'),
      array('id' =>483, 'makes_id' =>8, 'code' =>'TRANSCONN', 'name' =>'Transit Connect'),
      array('id' =>484, 'makes_id' =>8, 'code' =>'WINDST', 'name' =>'Windstar'),
      array('id' =>485, 'makes_id' =>8, 'code' =>'FORDZX2', 'name' =>'ZX2 Escort'),
      array('id' =>486, 'makes_id' =>8, 'code' =>'FOOTH','name' => 'Other Ford Models'),
      array('id' =>519, 'makes_id' =>9, 'code' =>'ACCORD', 'name' =>'Accord'),
      array('id' =>520, 'makes_id' =>9, 'code' =>'CIVIC', 'name' =>'Civic'),
      array('id' =>521, 'makes_id' =>9, 'code' =>'CRV', 'name' =>'CR-V'),
      array('id' =>522, 'makes_id' =>9, 'code' =>'CRZ', 'name' =>'CR-Z'),
      array('id' =>523, 'makes_id' =>9, 'code' =>'CRX','name' => 'CRX'),
      array('id' =>524, 'makes_id' =>9, 'code' =>'CROSSTOUR_MODELS', 'name' =>'Crosstour and Accord Crosstour Models (2)'),
      array('id' =>525, 'makes_id' =>9, 'code' =>'CROSSTOUR','name' => ' - Accord Crosstour'),
      array('id' =>526, 'makes_id' =>9, 'code' =>'HONCROSS', 'name' =>' - Crosstour'),
      array('id' =>527, 'makes_id' =>9, 'code' =>'HONDELSOL','name' => 'Del Sol'),
      array('id' =>528, 'makes_id' =>9, 'code' =>'ELEMENT','name' => 'Element'),
      array('id' =>529, 'makes_id' =>9, 'code' =>'FIT','name' => 'Fit'),
      array('id' =>530, 'makes_id' =>9, 'code' =>'INSIGHT', 'name' =>'Insight'),
      array('id' =>531, 'makes_id' =>9, 'code' =>'ODYSSEY','name' => 'Odyssey'),
      array('id' =>532, 'makes_id' =>9, 'code' =>'PASSPO', 'name' =>'Passport'),
      array('id' =>533, 'makes_id' =>9, 'code' =>'PILOT','name' => 'Pilot'),
      array('id' =>534, 'makes_id' =>9, 'code' =>'PRE','name' => 'Prelude'),
      array('id' =>535, 'makes_id' =>9, 'code' =>'RIDGELINE','name' => 'Ridgeline'),
      array('id' =>536, 'makes_id' =>9, 'code' =>'S2000', 'name' =>'S2000'),
      array('id' =>537, 'makes_id' =>9, 'code' =>'HONOTH','name' => 'Other Honda Models'),
      array('id' =>538, 'makes_id' =>10, 'code' =>'HUMMER', 'name' =>'H1'),
      array('id' =>539, 'makes_id' =>10, 'code' =>'H2','name' => 'H2'),
      array('id' =>540, 'makes_id' =>10, 'code' =>'H3','name' => 'H3'),
      array('id' =>541, 'makes_id' =>10, 'code' =>'H3T','name' => 'H3T'),
      array('id' =>542, 'makes_id' =>10, 'code' =>'AMGOTH', 'name' =>'Other Hummer Models'),
      array('id' =>543, 'makes_id' =>11, 'code' =>'ACCENT','name' => 'Accent'),
      array('id' =>544, 'makes_id' =>11, 'code' =>'AZERA', 'name' =>'Azera'),
      array('id' =>545, 'makes_id' =>11, 'code' =>'ELANTR', 'name' =>'Elantra'),
      array('id' =>546, 'makes_id' =>11, 'code' =>'HYUELANCPE','name' => 'Elantra Coupe'),
      array('id' =>547, 'makes_id' =>11, 'code' =>'ELANTOUR', 'name' =>'Elantra Touring'),
      array('id' =>548, 'makes_id' =>11, 'code' =>'ENTOURAGE', 'name' =>'Entourage'),
      array('id' =>549, 'makes_id' =>11, 'code' =>'EQUUS','name' => 'Equus'),
      array('id' =>550, 'makes_id' =>11, 'code' =>'HYUEXCEL', 'name' =>'Excel'),
      array('id' =>551, 'makes_id' =>11, 'code' =>'GENESIS', 'name' =>'Genesis'),
      array('id' =>552, 'makes_id' =>11, 'code' =>'GENESISCPE','name' => 'Genesis Coupe'),
      array('id' =>553, 'makes_id' =>11, 'code' =>'SANTAFE', 'name' =>'Santa Fe'),
      array('id' =>554, 'makes_id' =>11, 'code' =>'SCOUPE','name' => 'Scoupe'),
      array('id' =>555, 'makes_id' =>11, 'code' =>'SONATA', 'name' =>'Sonata'),
      array('id' =>556, 'makes_id' =>11, 'code' =>'TIBURO','name' => 'Tiburon'),
      array('id' =>557, 'makes_id' =>11, 'code' =>'TUCSON','name' => 'Tucson'),
      array('id' =>558, 'makes_id' =>11, 'code' =>'VELOSTER','name' => 'Veloster'),
      array('id' =>559, 'makes_id' =>11, 'code' =>'VERACRUZ','name' => 'Veracruz'),
      array('id' =>560, 'makes_id' =>11, 'code' =>'XG300', 'name' =>'XG300'),
      array('id' =>561, 'makes_id' =>11, 'code' =>'XG350','name' => 'XG350'),
      array('id' =>562, 'makes_id' =>11, 'code' =>'HYUOTH','name' => 'Other Hyundai Models'),
      array('id' =>563, 'makes_id' =>12, 'code' =>'EX_MODELS', 'name' =>'EX Models (2)'),
      array('id' =>564, 'makes_id' =>12, 'code' =>'EX35', 'name' =>'EX35'),
      array('id' =>565, 'makes_id' =>12, 'code' =>'EX37','name' => 'EX37'),
      array('id' =>566, 'makes_id' =>12, 'code' =>'FX_MODELS', 'name' =>'FX Models (4)'),
      array('id' =>567, 'makes_id' =>12, 'code' =>'FX35', 'name' =>'FX35'),
      array('id' =>568, 'makes_id' =>12, 'code' =>'FX37', 'name' =>'FX37'),
      array('id' =>569, 'makes_id' =>12, 'code' =>'FX45', 'name' =>'FX45'),
      array('id' =>570, 'makes_id' =>12, 'code' =>'FX50', 'name' =>'FX50'),
      array('id' =>571, 'makes_id' =>12, 'code' =>'G_MODELS','name' => 'G Models (4)'),
      array('id' =>572, 'makes_id' =>12, 'code' =>'G20', 'name' =>'G20'),
      array('id' =>573, 'makes_id' =>12, 'code' =>'G25','name' => 'G25'),
      array('id' =>574, 'makes_id' =>12, 'code' =>'G35', 'name' =>'G35'),
      array('id' =>575, 'makes_id' =>12, 'code' =>'G37', 'name' =>'G37'),
      array('id' =>576, 'makes_id' =>12, 'code' =>'I_MODELS','name' => 'I Models (2)'),
      array('id' =>577, 'makes_id' =>12, 'code' =>'I30', 'name' =>'I30'),
      array('id' =>578, 'makes_id' =>12, 'code' =>'I35', 'name' =>'I35'),
      array('id' =>579, 'makes_id' =>12, 'code' =>'J_MODELS', 'name' =>'J Models (1)'),
      array('id' =>580, 'makes_id' =>12, 'code' =>'J30','name' => 'J30'),
      array('id' =>581, 'makes_id' =>12, 'code' =>'JX_MODELS','name' => 'JX Models (1)'),
      array('id' =>582, 'makes_id' =>12, 'code' =>'JX35', 'name' =>'JX35'),
      array('id' =>583, 'makes_id' =>12, 'code' =>'M_MODELS', 'name' =>'M Models (6)'),
      array('id' =>584, 'makes_id' =>12, 'code' =>'M30','name' => 'M30'),
      array('id' =>585, 'makes_id' =>12, 'code' =>'M35','name' => 'M35'),
      array('id' =>586, 'makes_id' =>12, 'code' =>'M35HYBRID', 'name' =>'M35h'),
      array('id' =>587, 'makes_id' =>12, 'code' =>'M37','name' => 'M37'),
      array('id' =>588, 'makes_id' =>12, 'code' =>'M45', 'name' =>'M45'),
      array('id' =>589, 'makes_id' =>12, 'code' =>'M56','name' => 'M56'),
      array('id' =>590, 'makes_id' =>12, 'code' =>'Q_MODELS','name' => 'Q Models (1)'),
      array('id' =>591, 'makes_id' =>12, 'code' =>'Q45', 'name' =>' - Q45'),
      array('id' =>592, 'makes_id' =>12, 'code' =>'QX_MODELS','name' => 'QX Models (2)'),
      array('id' =>593, 'makes_id' =>12, 'code' =>'QX4','name' => ' - QX4'),
      array('id' =>594, 'makes_id' =>12, 'code' =>'QX56','name' => ' - QX56'),
      array('id' =>595, 'makes_id' =>12, 'code' =>'INFOTH','name' => 'Other Infiniti Models'),
      array('id' =>596, 'makes_id' =>13, 'code' =>'AMIGO', 'name' =>'Amigo'),
      array('id' =>597, 'makes_id' =>13, 'code' =>'ASCENDER','name' => 'Ascender'),
      array('id' =>598, 'makes_id' =>13, 'code' =>'AXIOM','name' => 'Axiom'),
      array('id' =>599, 'makes_id' =>13, 'code' =>'HOMBRE','name' => 'Hombre'),
      array('id' =>600, 'makes_id' =>13, 'code' =>'I280', 'name' =>'i-280'),
      array('id' =>601, 'makes_id' =>13, 'code' =>'I290', 'name' =>'i-290'),
      array('id' =>602, 'makes_id' =>13, 'code' =>'I350', 'name' =>'i-350'),
      array('id' =>603, 'makes_id' =>13, 'code' =>'I370', 'name' =>'i-370'),
      array('id' =>604, 'makes_id' =>13, 'code' =>'ISUMARK', 'name' =>'I-Mark'),
      array('id' =>605, 'makes_id' =>13, 'code' =>'ISUIMP','name' => 'Impulse'),
      array('id' =>606, 'makes_id' =>13, 'code' =>'OASIS', 'name' =>'Oasis'),
      array('id' =>607, 'makes_id' =>13, 'code' =>'ISUPU', 'name' =>'Pickup'),
      array('id' =>608, 'makes_id' =>13, 'code' =>'RODEO','name' => 'Rodeo'),
      array('id' =>609, 'makes_id' =>13, 'code' =>'STYLUS','name' => 'Stylus'),
      array('id' =>610, 'makes_id' =>13, 'code' =>'TROOP','name' => 'Trooper'),
      array('id' =>611, 'makes_id' =>13, 'code' =>'TRP2','name' => 'Trooper II'),
      array('id' =>612, 'makes_id' =>13, 'code' =>'VEHICROSS','name' => 'VehiCROSS'),
      array('id' =>613, 'makes_id' =>13, 'code' =>'ISUOTH', 'name' =>'Other Isuzu Models'),
      array('id' =>614, 'makes_id' =>14, 'code' =>'STYPE', 'name' =>'S-Type'),
      array('id' =>615, 'makes_id' =>14, 'code' =>'XTYPE','name' => 'X-Type'),
      array('id' =>616, 'makes_id' =>14, 'code' =>'XF', 'name' =>'XF'),
      array('id' =>617, 'makes_id' =>14, 'code' =>'XJ_SERIES', 'name' =>'XJ Series (10)'),
      array('id' =>618, 'makes_id' =>14, 'code' =>'JAGXJ12','name' => 'XJ12'),
      array('id' =>619, 'makes_id' =>14, 'code' =>'JAGXJ6', 'name' =>'XJ6'),
      array('id' =>620, 'makes_id' =>14, 'code' =>'JAGXJR','name' => 'XJR'),
      array('id' =>621, 'makes_id' =>14, 'code' =>'JAGXJRS', 'name' =>'XJR-S'),
      array('id' =>622, 'makes_id' =>14, 'code' =>'JAGXJS', 'name' =>'XJS'),
      array('id' =>623, 'makes_id' =>14, 'code' =>'VANDEN', 'name' =>'XJ Vanden Plas'),
      array('id' =>624, 'makes_id' =>14, 'code' =>'XJ', 'name' =>'XJ'),
      array('id' =>625, 'makes_id' =>14, 'code' =>'XJ8','name' => 'XJ8'),
      array('id' =>626, 'makes_id' =>14, 'code' =>'XJ8L','name' => 'XJ8 L'),
      array('id' =>627, 'makes_id' =>14, 'code' =>'XJSPORT', 'name' =>'XJ Sport'),
      array('id' =>628, 'makes_id' =>14, 'code' =>'XK_SERIES', 'name' =>'XK Series (3)'),
      array('id' =>629, 'makes_id' =>14, 'code' =>'JAGXK8', 'name' =>'XK8'),
      array('id' =>630, 'makes_id' =>14, 'code' =>'XK', 'name' =>'XK'),
      array('id' =>631, 'makes_id' =>14, 'code' =>'XKR','name' => 'XKR'),
      array('id' =>632, 'makes_id' =>14, 'code' =>'JAGOTH', 'name' =>'Other Jaguar Models'),
      array('id' =>633, 'makes_id' =>15, 'code' =>'CHER','name' =>'Cherokee'),
      array('id' =>634, 'makes_id' =>15, 'code' =>'JEEPCJ','name' => 'CJ'),
      array('id' =>635, 'makes_id' =>15, 'code' =>'COMANC','name' => 'Comanche'),
      array('id' =>636, 'makes_id' =>15, 'code' =>'COMMANDER','name' => 'Commander'),
      array('id' =>637, 'makes_id' =>15, 'code' =>'COMPASS', 'name' =>'Compass'),
      array('id' =>638, 'makes_id' =>15, 'code' =>'JEEPGRAND', 'name' =>'Grand Cherokee'),
      array('id' =>639, 'makes_id' =>15, 'code' =>'GRWAG', 'name' =>'Grand Wagoneer'),
      array('id' =>640, 'makes_id' =>15, 'code' =>'LIBERTY', 'name' =>'Liberty'),
      array('id' =>641, 'makes_id' =>15, 'code' =>'PATRIOT', 'name' =>'Patriot'),
      array('id' =>642, 'makes_id' =>15, 'code' =>'JEEPPU', 'name' =>'Pickup'),
      array('id' =>643, 'makes_id' =>15, 'code' =>'SCRAMBLE','name' => 'Scrambler'),
      array('id' =>644, 'makes_id' =>15, 'code' =>'WAGONE', 'name' =>'Wagoneer'),
      array('id' =>645, 'makes_id' =>15, 'code' =>'WRANGLER','name' => 'Wrangler'),
      array('id' =>646, 'makes_id' =>15, 'code' =>'JEOTH','name' => 'Other Jeep Models'),
      array('id' =>647, 'makes_id' =>16, 'code' =>'AMANTI', 'name' =>'Amanti'),
      array('id' =>648, 'makes_id' =>16, 'code' =>'BORREGO','name' => 'Borrego'),
      array('id' =>649, 'makes_id' =>16, 'code' =>'FORTE','name' => 'Forte'),
      array('id' =>650, 'makes_id' =>16, 'code' =>'FORTEKOUP','name' => 'Forte Koup'),
      array('id' =>651, 'makes_id' =>16, 'code' =>'OPTIMA','name' => 'Optima'),
      array('id' =>652, 'makes_id' =>16, 'code' =>'RIO', 'name' =>'Rio'),
      array('id' =>653, 'makes_id' =>16, 'code' =>'RIO5','name' => 'Rio5'),
      array('id' =>654, 'makes_id' =>16, 'code' =>'RONDO','name' => 'Rondo'),
      array('id' =>655, 'makes_id' =>16, 'code' =>'SEDONA','name' => 'Sedona'),
      array('id' =>656, 'makes_id' =>16, 'code' =>'SEPHIA', 'name' =>'Sephia'),
      array('id' =>657, 'makes_id' =>16, 'code' =>'SORENTO', 'name' =>'Sorento'),
      array('id' =>658, 'makes_id' =>16, 'code' =>'SOUL','name' => 'Soul'),
      array('id' =>659, 'makes_id' =>16, 'code' =>'SPECTRA', 'name' =>'Spectra'),
      array('id' =>660, 'makes_id' =>16, 'code' =>'SPECTRA5', 'name' =>'Spectra5'),
      array('id' =>661, 'makes_id' =>16, 'code' =>'SPORTA', 'name' =>'Sportage'),
      array('id' =>662, 'makes_id' =>16, 'code' =>'KIAOTH', 'name' =>'Other Kia Models'),
      array('id' =>674, 'makes_id' =>17, 'code' =>'DEFEND', 'name' =>'Defender'),
      array('id' =>675, 'makes_id' =>17, 'code' =>'DISCOV', 'name' =>'Discovery'),
      array('id' =>676, 'makes_id' =>17, 'code' =>'FRELNDR','name' => 'Freelander'),
      array('id' =>677, 'makes_id' =>17, 'code' =>'LR2', 'name' =>'LR2'),
      array('id' =>678, 'makes_id' =>17, 'code' =>'LR3','name' => 'LR3'),
      array('id' =>679, 'makes_id' =>17, 'code' =>'LR4','name' => 'LR4'),
      array('id' =>680, 'makes_id' =>17, 'code' =>'RANGE','name' => 'Range Rover'),
      array('id' =>681, 'makes_id' =>17, 'code' =>'EVOQUE', 'name' =>'Range Rover Evoque'),
      array('id' =>682, 'makes_id' =>17, 'code' =>'RANGESPORT', 'name' =>'Range Rover Sport'),
      array('id' =>683, 'makes_id' =>17, 'code' =>'ROVOTH', 'name' =>'Other Land Rover Models'),
      array('id' =>684, 'makes_id' =>18, 'code' =>'CT_MODELS','name' => 'CT Models (1)'),
      array('id' =>685, 'makes_id' =>18, 'code' =>'CT200H','name' => 'CT 200h'),
      array('id' =>686, 'makes_id' =>18, 'code' =>'ES_MODELS', 'name' =>'ES Models (5)'),
      array('id' =>687, 'makes_id' =>18, 'code' =>'ES250', 'name' =>'ES 250'),
      array('id' =>688, 'makes_id' =>18, 'code' =>'ES300', 'name' =>'ES 300'),
      array('id' =>689, 'makes_id' =>18, 'code' =>'ES300H','name' => 'ES 300h'),
      array('id' =>690, 'makes_id' =>18, 'code' =>'ES330','name' => 'ES 330'),
      array('id' =>691, 'makes_id' =>18, 'code' =>'ES350','name' => 'ES 350'),
      array('id' =>692, 'makes_id' =>18, 'code' =>'GS_MODELS','name' => 'GS Models (6)'),
      array('id' =>693, 'makes_id' =>18, 'code' =>'GS300','name' => 'GS 300'),
      array('id' =>694, 'makes_id' =>18, 'code' =>'GS350', 'name' =>'GS 350'),
      array('id' =>695, 'makes_id' =>18, 'code' =>'GS400','name' => 'GS 400'),
      array('id' =>696, 'makes_id' =>18, 'code' =>'GS430', 'name' =>'GS 430'),
      array('id' =>697, 'makes_id' =>18, 'code' =>'GS450H','name' => 'GS 450h'),
      array('id' =>698, 'makes_id' =>18, 'code' =>'GS460', 'name' =>'GS 460'),
      array('id' =>699, 'makes_id' =>18, 'code' =>'GX_MODELS', 'name' =>'GX Models (2)'),
      array('id' =>700, 'makes_id' =>18, 'code' =>'GX460','name' => 'GX 460'),
      array('id' =>701, 'makes_id' =>18, 'code' =>'GX470', 'name' =>'GX 470'),
      array('id' =>702, 'makes_id' =>18, 'code' =>'HS_MODELS', 'name' =>'HS Models (1)'),
      array('id' =>703, 'makes_id' =>18, 'code' =>'HS250H','name' => 'HS 250h'),
      array('id' =>704, 'makes_id' =>18, 'code' =>'IS_MODELS','name' => 'IS Models (6)'),
      array('id' =>705, 'makes_id' =>18, 'code' =>'IS250', 'name' =>'IS 250'),
      array('id' =>706, 'makes_id' =>18, 'code' =>'IS250C', 'name' =>'IS 250C'),
      array('id' =>707, 'makes_id' =>18, 'code' =>'IS300', 'name' =>'IS 300'),
      array('id' =>708, 'makes_id' =>18, 'code' =>'IS350','name' => 'IS 350'),
      array('id' =>709, 'makes_id' =>18, 'code' =>'IS350C', 'name' =>'IS 350C'),
      array('id' =>710, 'makes_id' =>18, 'code' =>'ISF', 'name' =>'IS F'),
      array('id' =>711, 'makes_id' =>18, 'code' =>'LEXLFA', 'name' =>'LFA'),
      array('id' =>712, 'makes_id' =>18, 'code' =>'LS_MODELS','name' => 'LS Models (4)'),
      array('id' =>713, 'makes_id' =>18, 'code' =>'LS400', 'name' =>'LS 400'),
      array('id' =>714, 'makes_id' =>18, 'code' =>'LS430', 'name' =>'LS 430'),
      array('id' =>715, 'makes_id' =>18, 'code' =>'LS460', 'name' =>'LS 460'),
      array('id' =>716, 'makes_id' =>18, 'code' =>'LS600H', 'name' =>'LS 600h'),
      array('id' =>717, 'makes_id' =>18, 'code' =>'LX_MODELS','name' => 'LX Models (3)'),
      array('id' =>718, 'makes_id' =>18, 'code' =>'LX450', 'name' =>'LX 450'),
      array('id' =>719, 'makes_id' =>18, 'code' =>'LX470', 'name' =>'LX 470'),
      array('id' =>720, 'makes_id' =>18, 'code' =>'LX570', 'name' =>'LX 570'),
      array('id' =>721, 'makes_id' =>18, 'code' =>'RX_MODELS', 'name' =>'RX Models (5)'),
      array('id' =>722, 'makes_id' =>18, 'code' =>'RX300', 'name' =>'RX 300'),
      array('id' =>723, 'makes_id' =>18, 'code' =>'RX330', 'name' =>'RX 330'),
      array('id' =>724, 'makes_id' =>18, 'code' =>'RX350', 'name' =>'RX 350'),
      array('id' =>725, 'makes_id' =>18, 'code' =>'RX400H','name' => 'RX 400h'),
      array('id' =>726, 'makes_id' =>18, 'code' =>'RX450H', 'name' =>'RX 450h'),
      array('id' =>727, 'makes_id' =>18, 'code' =>'SC_MODELS','name' => 'SC Models (3)'),
      array('id' =>728, 'makes_id' =>18, 'code' =>'SC300','name' => 'SC 300'),
      array('id' =>729, 'makes_id' =>18, 'code' =>'SC400', 'name' =>'SC 400'),
      array('id' =>730, 'makes_id' =>18, 'code' =>'SC430', 'name' =>'SC 430'),
      array('id' =>731, 'makes_id' =>18, 'code' =>'LEXOTH', 'name' =>'Other Lexus Models'),
      array('id' =>763, 'makes_id' =>19, 'code' =>'57MAYBACH', 'name' =>'57'),
      array('id' =>764, 'makes_id' =>19, 'code' =>'62MAYBACH', 'name' =>'62'),
      array('id' =>765, 'makes_id' =>19, 'code' =>'UNAVAILMAY','name' => 'Other Maybach Models'),
      array('id' =>766, 'makes_id' =>20, 'code' =>'MAZDA323','name' => '323'),
      array('id' =>767, 'makes_id' =>20, 'code' =>'MAZDA626', 'name' =>'626'),
      array('id' =>768, 'makes_id' =>20, 'code' =>'929','name' => '929'),
      array('id' =>769, 'makes_id' =>20, 'code' =>'B-SERIES','name' => 'B-Series Pickup'),
      array('id' =>770, 'makes_id' =>20, 'code' =>'CX-5', 'name' =>'CX-5'),
      array('id' =>771, 'makes_id' =>20, 'code' =>'CX-7', 'name' =>'CX-7'),
      array('id' =>772, 'makes_id' =>20, 'code' =>'CX-9', 'name' =>'CX-9'),
      array('id' =>773, 'makes_id' =>20, 'code' =>'GLC','name' => 'GLC'),
      array('id' =>774, 'makes_id' =>20, 'code' =>'MAZDA2_DEMIO', 'name' =>'Mazda2 / Demio'),
      array('id' =>775, 'makes_id' =>20, 'code' =>'MAZDA3', 'name' =>'MAZDA3'),
      array('id' =>776, 'makes_id' =>20, 'code' =>'MAZDA5', 'name' =>'MAZDA5'),
      array('id' =>777, 'makes_id' =>20, 'code' =>'MAZDA6', 'name' =>'MAZDA6'),
      array('id' =>778, 'makes_id' =>20, 'code' =>'MAZDASPD3', 'name' =>'MAZDASPEED3'),
      array('id' =>779, 'makes_id' =>20, 'code' =>'MAZDASPD6', 'name' =>'MAZDASPEED6'),
      array('id' =>780, 'makes_id' =>20, 'code' =>'MIATA', 'name' =>'Miata MX5'),
      array('id' =>781, 'makes_id' =>20, 'code' =>'MILL','name' => 'Millenia'),
      array('id' =>782, 'makes_id' =>20, 'code' =>'MPV', 'name' =>'MPV'),
      array('id' =>783, 'makes_id' =>20, 'code' =>'MX3', 'name' =>'MX3'),
      array('id' =>784, 'makes_id' =>20, 'code' =>'MX6','name' => 'MX6'),
      array('id' =>785, 'makes_id' =>20, 'code' =>'NAVAJO','name' => 'Navajo'),
      array('id' =>786, 'makes_id' =>20, 'code' =>'PROTE', 'name' =>'Protege'),
      array('id' =>787, 'makes_id' =>20, 'code' =>'PROTE5', 'name' =>'Protege5'),
      array('id' =>788, 'makes_id' =>20, 'code' =>'RX7','name' => 'RX-7'),
      array('id' =>789, 'makes_id' =>20, 'code' =>'RX8','name' => 'RX-8'),
      array('id' =>790, 'makes_id' =>20, 'code' =>'TRIBUTE', 'name' =>'Tribute'),
      array('id' =>791, 'makes_id' =>20, 'code' =>'MAZOTH','name' => 'Other Mazda Models'),
      array('id' =>793, 'makes_id' =>21, 'code' =>'190_CLASS', 'name' =>'190 Class (2)'),
      array('id' =>794, 'makes_id' =>21, 'code' =>'190D', 'name' =>'190D'),
      array('id' =>795, 'makes_id' =>21, 'code' =>'190E', 'name' =>'190E'),
      array('id' =>796, 'makes_id' =>21, 'code' =>'240_CLASS','name' => '240 Class (1)'),
      array('id' =>797, 'makes_id' =>21, 'code' =>'240D', 'name' =>'240D'),
      array('id' =>798, 'makes_id' =>21, 'code' =>'300_CLASS_E_CLASS', 'name' =>'300 Class / E Class (6)'),
      array('id' =>799, 'makes_id' =>21, 'code' =>'300CD', 'name' =>'300CD'),
      array('id' =>800, 'makes_id' =>21, 'code' =>'300CE','name' => '300CE'),
      array('id' =>801, 'makes_id' =>21, 'code' =>'300D', '300D'),
      array('id' =>802, 'makes_id' =>21, 'code' =>'300E', 'name' =>'300E'),
      array('id' =>803, 'makes_id' =>21, 'code' =>'300TD', 'name' =>'300TD'),
      array('id' =>804, 'makes_id' =>21, 'code' =>'300TE','name' => '300TE'),
      array('id' =>805, 'makes_id' =>21, 'code' =>'C_CLASS', 'name' =>'C Class (13)'),
      array('id' =>806, 'makes_id' =>21, 'code' =>'C220', 'name' =>'C220'),
      array('id' =>807, 'makes_id' =>21, 'code' =>'C230', 'name' =>'C230'),
      array('id' =>808, 'makes_id' =>21, 'code' =>'C240', 'name' =>'C240'),
      array('id' =>809, 'makes_id' =>21, 'code' =>'C250','name' => 'C250'),
      array('id' =>810, 'makes_id' =>21, 'code' =>'C280','name' => 'C280'),
      array('id' =>811, 'makes_id' =>21, 'code' =>'C300','name' => 'C300'),
      array('id' =>812, 'makes_id' =>21, 'code' =>'C320', 'name' =>'C320'),
      array('id' =>813, 'makes_id' =>21, 'code' =>'C32AMG', 'name' =>'C32 AMG'),
      array('id' =>814, 'makes_id' =>21, 'code' =>'C350', 'name' =>'C350'),
      array('id' =>815, 'makes_id' =>21, 'code' =>'C36AMG', 'name' =>'C36 AMG'),
      array('id' =>816, 'makes_id' =>21, 'code' =>'C43AMG', 'name' =>'C43 AMG'),
      array('id' =>817, 'makes_id' =>21, 'code' =>'C55AMG', 'name' =>'C55 AMG'),
      array('id' =>818, 'makes_id' =>21, 'code' =>'C63AMG', 'name' =>'C63 AMG'),
      array('id' =>819, 'makes_id' =>21, 'code' =>'CL_CLASS', 'name' =>'CL Class (6)'),
      array('id' =>820, 'makes_id' =>21, 'code' =>'CL500', 'name' =>'CL500'),
      array('id' =>821, 'makes_id' =>21, 'code' =>'CL550', 'name' =>'CL550'),
      array('id' =>822, 'makes_id' =>21, 'code' =>'CL55AMG', 'name' =>'CL55 AMG'),
      array('id' =>823, 'makes_id' =>21, 'code' =>'CL600', 'name' =>'CL600'),
      array('id' =>824, 'makes_id' =>21, 'code' =>'CL63AMG','name' => 'CL63 AMG'),
      array('id' =>825, 'makes_id' =>21, 'code' =>'CL65AMG', 'name' =>'CL65 AMG'),
      array('id' =>826, 'makes_id' =>21, 'code' =>'CLK_CLASS','name' => 'CLK Class (7)'),
      array('id' =>827, 'makes_id' =>21, 'code' =>'CLK320', 'name' =>'CLK320'),
      array('id' =>828, 'makes_id' =>21, 'code' =>'CLK350', 'name' =>'CLK350'),
      array('id' =>829, 'makes_id' =>21, 'code' =>'CLK430', 'name' =>'CLK430'),
      array('id' =>830, 'makes_id' =>21, 'code' =>'CLK500', 'name' =>'CLK500'),
      array('id' =>831, 'makes_id' =>21, 'code' =>'CLK550', 'name' =>'CLK550'),
      array('id' =>832, 'makes_id' =>21, 'code' =>'CLK55AMG', 'name' =>'CLK55 AMG'),
      array('id' =>833, 'makes_id' =>21, 'code' =>'CLK63AMG', 'name' =>'CLK63 AMG'),
      array('id' =>834, 'makes_id' =>21, 'code' =>'CLS_CLASS','name' => 'CLS Class (4)'),
      array('id' =>835, 'makes_id' =>21, 'code' =>'CLS500', 'name' =>'CLS500'),
      array('id' =>836, 'makes_id' =>21, 'code' =>'CLS550','name' => 'CLS550'),
      array('id' =>837, 'makes_id' =>21, 'code' =>'CLS55AMG','name' => 'CLS55 AMG'),
      array('id' =>838, 'makes_id' =>21, 'code' =>'CLS63AMG','name' => 'CLS63 AMG'),
      array('id' =>839, 'makes_id' =>21, 'code' =>'E_CLASS','name' => 'E Class (18)'),
      array('id' =>840, 'makes_id' =>21, 'code' =>'260E','name' => '260E'),
      array('id' =>841, 'makes_id' =>21, 'code' =>'280CE', 'name' =>'280CE'),
      array('id' =>842, 'makes_id' =>21, 'code' =>'280E', 'name' =>'280E'),
      array('id' =>843, 'makes_id' =>21, 'code' =>'400E','name' => '400E'),
      array('id' =>844, 'makes_id' =>21, 'code' =>'500E', 'name' =>'500E'),
      array('id' =>845, 'makes_id' =>21, 'code' =>'E300','name' => 'E300'),
      array('id' =>846, 'makes_id' =>21, 'code' =>'E320', 'name' =>'E320'),
      array('id' =>847, 'makes_id' =>21, 'code' =>'E320BLUE','name' => 'E320 Bluetec'),
      array('id' =>848, 'makes_id' =>21, 'code' =>'E320CDI', 'name' =>'E320 CDI'),
      array('id' =>849, 'makes_id' =>21, 'code' =>'E350', 'name' =>'E350'),
      array('id' =>850, 'makes_id' =>21, 'code' =>'E350BLUE', 'name' =>'E350 Bluetec'),
      array('id' =>851, 'makes_id' =>21, 'code' =>'E400', 'name' =>'E400 Hybrid'),
      array('id' =>852, 'makes_id' =>21, 'code' =>'E420', 'name' =>'E420'),
      array('id' =>853, 'makes_id' =>21, 'code' =>'E430', 'name' =>'E430'),
      array('id' =>854, 'makes_id' =>21, 'code' =>'E500', 'name' =>'E500'),
      array('id' =>855, 'makes_id' =>21, 'code' =>'E550', 'name' =>'E550'),
      array('id' =>856, 'makes_id' =>21, 'code' =>'E55AMG', 'name' =>'E55 AMG'),
      array('id' =>857, 'makes_id' =>21, 'code' =>'E63AMG','name' => 'E63 AMG'),
      array('id' =>858, 'makes_id' =>21, 'code' =>'G_CLASS','name' => 'G Class (4)'),
      array('id' =>859, 'makes_id' =>21, 'code' =>'G500', 'name' =>'G500'),
      array('id' =>860, 'makes_id' =>21, 'code' =>'G550', 'name' =>'G550'),
      array('id' =>861, 'makes_id' =>21, 'code' =>'G55AMG', 'name' =>'G55 AMG'),
      array('id' =>862, 'makes_id' =>21, 'code' =>'G63AMG', 'name' =>'G63 AMG'),
      array('id' =>863, 'makes_id' =>21, 'code' =>'GL_CLASS','name' => 'GL Class (5)'),
      array('id' =>864, 'makes_id' =>21, 'code' =>'GL320BLUE', 'name' =>'GL320 Bluetec'),
      array('id' =>865, 'makes_id' =>21, 'code' =>'GL320CDI', 'name' =>'GL320 CDI'),
      array('id' =>866, 'makes_id' =>21, 'code' =>'GL350BLUE','name' => 'GL350 Bluetec'),
      array('id' =>867, 'makes_id' =>21, 'code' =>'GL450', 'name' =>'GL450'),
      array('id' =>868, 'makes_id' =>21, 'code' =>'GL550','name' => 'GL550'),
      array('id' =>869, 'makes_id' =>21, 'code' =>'GLK_CLASS', 'name' =>'GLK Class (1)'),
      array('id' =>870, 'makes_id' =>21, 'code' =>'GLK350', 'name' =>'GLK350'),
      array('id' =>871, 'makes_id' =>21, 'code' =>'M_CLASS','name' => 'M Class (11)'),
      array('id' =>872, 'makes_id' =>21, 'code' =>'ML320', 'name' =>'ML320'),
      array('id' =>873, 'makes_id' =>21, 'code' =>'ML320BLUE', 'name' =>'ML320 Bluetec'),
      array('id' =>874, 'makes_id' =>21, 'code' =>'ML320CDI', 'name' =>'ML320 CDI'),
      array('id' =>875, 'makes_id' =>21, 'code' =>'ML350','name' => 'ML350'),
      array('id' =>876, 'makes_id' =>21, 'code' =>'ML350BLUE','name' => 'ML350 Bluetec'),
      array('id' =>877, 'makes_id' =>21, 'code' =>'ML430', 'name' =>'ML430'),
      array('id' =>878, 'makes_id' =>21, 'code' =>'ML450HY', 'name' =>'ML450 Hybrid'),
      array('id' =>879, 'makes_id' =>21, 'code' =>'ML500', 'name' =>'ML500'),
      array('id' =>880, 'makes_id' =>21, 'code' =>'ML550', 'name' =>'ML550'),
      array('id' =>881, 'makes_id' =>21, 'code' =>'ML55AMG', 'name' =>'ML55 AMG'),
      array('id' =>882, 'makes_id' =>21, 'code' =>'ML63AMG', 'name' =>'ML63 AMG'),
      array('id' =>883, 'makes_id' =>21, 'code' =>'R_CLASS', 'name' =>'R Class (6)'),
      array('id' =>884, 'makes_id' =>21, 'code' =>'R320BLUE','name' => 'R320 Bluetec'),
      array('id' =>885, 'makes_id' =>21, 'code' =>'R320CDI', 'name' =>'R320 CDI'),
      array('id' =>886, 'makes_id' =>21, 'code' =>'R350', 'name' =>'R350'),
      array('id' =>887, 'makes_id' =>21, 'code' =>'R350BLUE', 'name' =>'R350 Bluetec'),
      array('id' =>888, 'makes_id' =>21, 'code' =>'R500', 'name' =>'R500'),
      array('id' =>889, 'makes_id' =>21, 'code' =>'R63AMG', 'name' =>'R63 AMG'),
      array('id' =>890, 'makes_id' =>21, 'code' =>'S_CLASS', 'name' =>'S Class (30)'),
      array('id' =>891, 'makes_id' =>21, 'code' =>'300SD', 'name' =>'300SD'),
      array('id' =>892, 'makes_id' =>21, 'code' =>'300SDL', 'name' =>'300SDL'),
      array('id' =>893, 'makes_id' =>21, 'code' =>'300SE', 'name' =>'300SE'),
      array('id' =>894, 'makes_id' =>21, 'code' =>'300SEL','name' => '300SEL'),
      array('id' =>895, 'makes_id' =>21, 'code' =>'350SD', 'name' =>'350SD'),
      array('id' =>896, 'makes_id' =>21, 'code' =>'350SDL','name' => '350SDL'),
      array('id' =>897, 'makes_id' =>21, 'code' =>'380SE', 'name' =>'380SE'),
      array('id' =>898, 'makes_id' =>21, 'code' =>'380SEC','name' => '380SEC'),
      array('id' =>899, 'makes_id' =>21, 'code' =>'380SEL', 'name' =>'380SEL'),
      array('id' =>900, 'makes_id' =>21, 'code' =>'400SE', 'name' =>'400SE'),
      array('id' =>901, 'makes_id' =>21, 'code' =>'400SEL', 'name' =>'400SEL'),
      array('id' =>902, 'makes_id' =>21, 'code' =>'420SEL', 'name' =>'420SEL'),
      array('id' =>903, 'makes_id' =>21, 'code' =>'500SEC', 'name' =>'500SEC'),
      array('id' =>904, 'makes_id' =>21, 'code' =>'500SEL', 'name' =>'500SEL'),
      array('id' =>905, 'makes_id' =>21, 'code' =>'560SEC', 'name' =>'560SEC'),
      array('id' =>906, 'makes_id' =>21, 'code' =>'560SEL', 'name' =>'560SEL'),
      array('id' =>907, 'makes_id' =>21, 'code' =>'600SEC','name' => '600SEC'),
      array('id' =>908, 'makes_id' =>21, 'code' =>'600SEL', 'name' =>'600SEL'),
      array('id' =>909, 'makes_id' =>21, 'code' =>'S320', 'name' =>'S320'),
      array('id' =>910, 'makes_id' =>21, 'code' =>'S350', 'name' =>'S350'),
      array('id' =>911, 'makes_id' =>21, 'code' =>'S350BLUE', 'name' =>'S350 Bluetec'),
      array('id' =>912, 'makes_id' =>21, 'code' =>'S400HY', 'name' =>'S400 Hybrid'),
      array('id' =>913, 'makes_id' =>21, 'code' =>'S420', 'name' =>'S420'),
      array('id' =>914, 'makes_id' =>21, 'code' =>'S430', 'name' =>'S430'),
      array('id' =>915, 'makes_id' =>21, 'code' =>'S500', 'name' =>'S500'),
      array('id' =>916, 'makes_id' =>21, 'code' =>'S550', 'name' =>'S550'),
      array('id' =>917, 'makes_id' =>21, 'code' =>'S55AMG','name' => 'S55 AMG'),
      array('id' =>918, 'makes_id' =>21, 'code' =>'S600', 'name' =>'S600'),
      array('id' =>919, 'makes_id' =>21, 'code' =>'S63AMG', 'name' =>'S63 AMG'),
      array('id' =>920, 'makes_id' =>21, 'code' =>'S65AMG', 'name' =>'S65 AMG'),
      array('id' =>921, 'makes_id' =>21, 'code' =>'SL_CLASS', 'name' =>'SL Class (13)'),
      array('id' =>922, 'makes_id' =>21, 'code' =>'300SL','name' => '300SL'),
      array('id' =>923, 'makes_id' =>21, 'code' =>'380SL', 'name' =>'380SL'),
      array('id' =>924, 'makes_id' =>21, 'code' =>'380SLC', 'name' =>'380SLC'),
      array('id' =>925, 'makes_id' =>21, 'code' =>'500SL', 'name' =>'500SL'),
      array('id' =>926, 'makes_id' =>21, 'code' =>'560SL', 'name' =>'560SL'),
      array('id' =>927, 'makes_id' =>21, 'code' =>'600SL', 'name' =>'600SL'),
      array('id' =>928, 'makes_id' =>21, 'code' =>'SL320','name' => 'SL320'),
      array('id' =>929, 'makes_id' =>21, 'code' =>'SL500','name' => 'SL500'),
      array('id' =>930, 'makes_id' =>21, 'code' =>'SL550','name' => 'SL550'),
      array('id' =>931, 'makes_id' =>21, 'code' =>'SL55AMG','name' => 'SL55 AMG'),
      array('id' =>932, 'makes_id' =>21, 'code' =>'SL600', 'name' =>'SL600'),
      array('id' =>933, 'makes_id' =>21, 'code' =>'SL63AMG', 'name' =>'SL63 AMG'),
      array('id' =>934, 'makes_id' =>21, 'code' =>'SL65AMG', 'name' =>'SL65 AMG'),
      array('id' =>935, 'makes_id' =>21, 'code' =>'SLK_CLASS','name' => 'SLK Class (8)'),
      array('id' =>936, 'makes_id' =>21, 'code' =>'SLK230', 'name' =>'SLK230'),
      array('id' =>937, 'makes_id' =>21, 'code' =>'SLK250', 'name' =>'SLK250'),
      array('id' =>938, 'makes_id' =>21, 'code' =>'SLK280', 'name' =>'SLK280'),
      array('id' =>939, 'makes_id' =>21, 'code' =>'SLK300', 'name' =>'SLK300'),
      array('id' =>940, 'makes_id' =>21, 'code' =>'SLK320', 'name' =>'SLK320'),
      array('id' =>941, 'makes_id' =>21, 'code' =>'SLK32AMG','name' => 'SLK32 AMG'),
      array('id' =>942, 'makes_id' =>21, 'code' =>'SLK350','name' => 'SLK350'),
      array('id' =>943, 'makes_id' =>21, 'code' =>'SLK55AMG', 'name' =>'SLK55 AMG'),
      array('id' =>944, 'makes_id' =>21, 'code' =>'SLR_CLASS','name' => 'SLR Class (1)'),
      array('id' =>945, 'makes_id' =>21, 'code' =>'SLR','name' => ' - SLR'),
      array('id' =>946, 'makes_id' =>21, 'code' =>'SLS_CLASS', 'name' =>'SLS Class (1)'),
      array('id' =>947, 'makes_id' =>21, 'code' =>'SLSAMG', 'name' =>' SLS AMG'),
      array('id' =>948, 'makes_id' =>21, 'code' =>'SPRINTER_CLASS', 'name' =>'Sprinter Class (1)'),
      array('id' =>949, 'makes_id' =>21, 'code' =>'MBSPRINTER', 'name' =>'Sprinter'),
      array('id' =>950, 'makes_id' =>21, 'code' =>'MBOTH','name' => 'Other Mercedes-Benz Models'),
      array('id' =>987, 'makes_id' =>22, 'code' =>'3000GT','name' => '3000GT'),
      array('id' =>988, 'makes_id' =>22, 'code' =>'CORD','name' => 'Cordia'),
      array('id' =>989, 'makes_id' =>22, 'code' =>'DIAMAN', 'name' =>'Diamante'),
      array('id' =>990, 'makes_id' =>22, 'code' =>'ECLIP','name' => 'Eclipse'),
      array('id' =>991, 'makes_id' =>22, 'code' =>'ENDEAVOR', 'name' =>'Endeavor'),
      array('id' =>992, 'makes_id' =>22, 'code' =>'MITEXP','name' => 'Expo'),
      array('id' =>993, 'makes_id' =>22, 'code' =>'GALANT','name' => 'Galant'),
      array('id' =>994, 'makes_id' =>22, 'code' =>'MITI', 'name' =>'i'),
      array('id' =>995, 'makes_id' =>22, 'code' =>'LANCERMITS', 'name' =>'Lancer'),
      array('id' =>996, 'makes_id' =>22, 'code' =>'LANCEREVO', 'name' =>'Lancer Evolution'),
      array('id' =>997, 'makes_id' =>22, 'code' =>'MITPU', 'name' =>'Mighty Max'),
      array('id' =>998, 'makes_id' =>22, 'code' =>'MIRAGE', 'name' =>'Mirage'),
      array('id' =>999, 'makes_id' =>22, 'code' =>'MONT','name' => 'Montero'),
      array('id' =>1000, 'makes_id' =>22,'code' => 'MONTSPORT','name' => 'Montero Sport'),
      array('id' =>1001, 'makes_id' =>22,'code' => 'OUTLANDER', 'name' =>'Outlander'),
      array('id' =>1002, 'makes_id' =>22,'code' => 'OUTLANDSPT', 'name' =>'Outlander Sport'),
      array('id' =>1003, 'makes_id' =>22,'code' => 'PRECIS','name' => 'Precis'),
      array('id' =>1004, 'makes_id' =>22,'code' => 'RAIDERMITS', 'name' =>'Raider'),
      array('id' =>1005, 'makes_id' =>22,'code' => 'SIGMA', 'name' =>'Sigma'),
      array('id' =>1006, 'makes_id' =>22,'code' => 'MITSTAR', 'name' =>'Starion'),
      array('id' =>1007, 'makes_id' =>22,'code' => 'TRED', 'name' =>'Tredia'),
      array('id' =>1008, 'makes_id' =>22,'code' => 'MITVAN','name' => 'Van'),
      array('id' =>1009, 'makes_id' =>22,'code' => 'MITOTH', 'name' =>'Other Mitsubishi Models'),
      array('id' =>1010, 'makes_id' =>23,'code' => 'NIS200SX','name' => '200SX'),
      array('id' =>1011, 'makes_id' =>23,'code' => '240SX', 'name' =>'240SX'),
      array('id' =>1012, 'makes_id' =>23,'code' => '300ZXTURBO','name' => '300ZX'),
      array('id' =>1013, 'makes_id' =>23,'code' => '350Z', 'name' =>'350Z'),
      array('id' =>1014, 'makes_id' =>23,'code' => '370Z', 'name' =>'370Z'),
      array('id' =>1015, 'makes_id' =>23,'code' => 'ALTIMA', 'name' =>'Altima'),
      array('id' =>1016, 'makes_id' =>23,'code' => 'PATHARMADA','name' => 'Armada'),
      array('id' =>1017, 'makes_id' =>23,'code' => 'AXXESS', 'name' =>'Axxess'),
      array('id' =>1018, 'makes_id' =>23,'code' => 'CUBE', 'name' =>'Cube'),
      array('id' =>1019, 'makes_id' =>23,'code' => 'FRONTI', 'name' =>'Frontier'),
      array('id' =>1020, 'makes_id' =>23,'code' => 'GT-R','name' => 'GT-R'),
      array('id' =>1021, 'makes_id' =>23, 'code' =>'JUKE','name' =>'Juke'),
      array('id' =>1022, 'makes_id' =>23, 'code' =>'LEAF','name' => 'Leaf'),
      array('id' =>1023, 'makes_id' =>23, 'code' =>'MAX', 'name' =>'Maxima'),
      array('id' =>1024, 'makes_id' =>23, 'code' =>'MURANO','name' => 'Murano'),
      array('id' =>1025, 'makes_id' =>23, 'code' =>'MURANOCROS','name' => 'Murano CrossCabriolet'),
      array('id' =>1026, 'makes_id' =>23, 'code' =>'NV', 'name' =>'NV'),
      array('id' =>1027, 'makes_id' =>23, 'code' =>'NX', 'name' =>'NX'),
      array('id' =>1028, 'makes_id' =>23, 'code' =>'PATH', 'name' =>'Pathfinder'),
      array('id' =>1029, 'makes_id' =>23, 'code' =>'NISPU', 'name' =>'Pickup'),
      array('id' =>1030, 'makes_id' =>23, 'code' =>'PULSAR','name' => 'Pulsar'),
      array('id' =>1031, 'makes_id' =>23, 'code' =>'QUEST', 'name' =>'Quest'),
      array('id' =>1032, 'makes_id' =>23, 'code' =>'ROGUE', 'name' =>'Rogue'),
      array('id' =>1033, 'makes_id' =>23, 'code' =>'SENTRA','name' => 'Sentra'),
      array('id' =>1034, 'makes_id' =>23, 'code' =>'STANZA','name' => 'Stanza'),
      array('id' =>1035, 'makes_id' =>23, 'code' =>'TITAN', 'name' =>'Titan'),
      array('id' =>1036, 'makes_id' =>23, 'code' =>'NISVAN','name' => 'Van'),
      array('id' =>1037, 'makes_id' =>23, 'code' =>'VERSA', 'name' =>'Versa'),
      array('id' =>1038, 'makes_id' =>23, 'code' =>'XTERRA','name' => 'Xterra'),
      array('id' =>1039, 'makes_id' =>23, 'code' =>'NISSOTH','name' => 'Other Nissan Models'),
      array('id' =>1058, 'makes_id' =>24, 'code' =>'405', 'name' =>'405'),
      array('id' =>1059, 'makes_id' =>24, 'code' =>'504', 'name' =>'504'),
      array('id' =>1060, 'makes_id' =>24, 'code' =>'505','name' => '505'),
      array('id' =>1061, 'makes_id' =>24, 'code' =>'604','name' => '604'),
      array('id' =>1062, 'makes_id' =>24, 'code' =>'UNAVAILPEU','name' => 'Other Peugeot Models'),
      array('id' =>1110, 'makes_id' =>25, 'code' =>'911','name' => '911'),
      array('id' =>1111, 'makes_id' =>25, 'code' =>'924','name' => '924'),
      array('id' =>1112, 'makes_id' =>25, 'code' =>'928','name' => '928'),
      array('id' =>1113, 'makes_id' =>25, 'code' =>'944','name' => '944'),
      array('id' =>1114, 'makes_id' =>25, 'code' =>'968','name' => '968'),
      array('id' =>1115, 'makes_id' =>25, 'code' =>'BOXSTE', 'name' =>'Boxster'),
      array('id' =>1116, 'makes_id' =>25, 'code' =>'CARRERAGT','name' => 'Carrera GT'),
      array('id' =>1117, 'makes_id' =>25, 'code' =>'CAYENNE', 'name' =>'Cayenne'),
      array('id' =>1118, 'makes_id' =>25, 'code' =>'CAYMAN', 'name' =>'Cayman'),
      array('id' =>1119, 'makes_id' =>25, 'code' =>'PANAMERA','name' => 'Panamera'),
      array('id' =>1120, 'makes_id' =>25, 'code' =>'POROTH', 'name' =>'Other Porsche Models'),
      array('id' =>1125, 'makes_id' =>26, 'code' =>'18I','name' => '18i'),
      array('id' =>1126, 'makes_id' =>26, 'code' =>'FU', 'name' =>'Fuego'),
      array('id' =>1127, 'makes_id' =>26, 'code' =>'LECAR','name' => 'Le Car'),
      array('id' =>1128, 'makes_id' =>26, 'code' =>'R18','name' => 'R18'),
      array('id' =>1129, 'makes_id' =>26, 'code' =>'RENSPORT','name' => 'Sportwagon'),
      array('id' =>1130, 'makes_id' =>26, 'code' =>'UNAVAILREN','name' => 'Other Renault Models'),
      array('id' =>1189, 'makes_id' =>27, 'code' =>'BAJA', 'name' =>'Baja'),
      array('id' =>1190, 'makes_id' =>27, 'code' =>'BRAT', 'name' =>'Brat'),
      array('id' =>1191, 'makes_id' =>27, 'code' =>'SUBBRZ','name' => 'BRZ'),
      array('id' =>1192, 'makes_id' =>27, 'code' =>'FOREST','name' => 'Forester'),
      array('id' =>1193, 'makes_id' =>27, 'code' =>'IMPREZ', 'name' =>'Impreza'),
      array('id' =>1194, 'makes_id' =>27, 'code' =>'IMPWRX', 'name' =>'Impreza WRX'),
      array('id' =>1195, 'makes_id' =>27, 'code' =>'JUSTY','name' => 'Justy'),
      array('id' =>1196, 'makes_id' =>27, 'code' =>'SUBL', 'name' =>'L Series'),
      array('id' =>1197, 'makes_id' =>27, 'code' =>'LEGACY','name' => 'Legacy'),
      array('id' =>1198, 'makes_id' =>27, 'code' =>'LOYALE','name' => 'Loyale'),
      array('id' =>1199, 'makes_id' =>27, 'code' =>'SUBOUTBK','name' => 'Outback'),
      array('id' =>1200, 'makes_id' =>27, 'code' =>'SVX', 'name' =>'SVX'),
      array('id' =>1201, 'makes_id' =>27, 'code' =>'B9TRIBECA', 'name' =>'Tribeca'),
      array('id' =>1202, 'makes_id' =>27, 'code' =>'XT', 'name' =>'XT'),
      array('id' =>1203, 'makes_id' =>27, 'code' =>'XVCRSSTREK', 'name' =>'XV Crosstrek'),
      array('id' =>1204, 'makes_id' =>27, 'code' =>'SUBOTH','name' => 'Other Subaru Models'),
      array('id' =>1205, 'makes_id' =>28, 'code' =>'AERIO', 'name' =>'Aerio'),
      array('id' =>1206, 'makes_id' =>28, 'code' =>'EQUATOR','name' => 'Equator'),
      array('id' =>1207, 'makes_id' =>28, 'code' =>'ESTEEM', 'name' =>'Esteem'),
      array('id' =>1208, 'makes_id' =>28, 'code' =>'FORENZA','name' => 'Forenza'),
      array('id' =>1209, 'makes_id' =>28, 'code' =>'GRANDV', 'name' =>'Grand Vitara'),
      array('id' =>1210, 'makes_id' =>28, 'code' =>'KIZASHI','name' => 'Kizashi'),
      array('id' =>1211, 'makes_id' =>28, 'code' =>'RENO', 'name' =>'Reno'),
      array('id' =>1212, 'makes_id' =>28, 'code' =>'SAMUR', 'name' =>'Samurai'),
      array('id' =>1213, 'makes_id' =>28, 'code' =>'SIDE', 'name' =>'Sidekick'),
      array('id' =>1214, 'makes_id' =>28, 'code' =>'SWIFT', 'name' =>'Swift'),
      array('id' =>1215, 'makes_id' =>28, 'code' =>'SX4', 'name' =>'SX4'),
      array('id' =>1216, 'makes_id' =>28, 'code' =>'VERONA', 'name' =>'Verona'),
      array('id' =>1217, 'makes_id' =>28, 'code' =>'VITARA','name' => 'Vitara'),
      array('id' =>1218, 'makes_id' =>28, 'code' =>'X90', 'name' =>'X-90'),
      array('id' =>1219, 'makes_id' =>28, 'code' =>'XL7', 'name' =>'XL7'),
      array('id' =>1220, 'makes_id' =>28, 'code' =>'SUZOTH','name' => 'Other Suzuki Models'),
      array('id' =>1221, 'makes_id' =>29, 'code' =>'ROADSTER','name' => 'Roadster'),
      array('id' =>1222, 'makes_id' =>30, 'code' =>'4RUN', 'name' =>'4Runner'),
      array('id' =>1223, 'makes_id' =>30, 'code' =>'AVALON', 'name' =>'Avalon'),
      array('id' =>1224, 'makes_id' =>30, 'code' =>'CAMRY', 'name' =>'Camry'),
      array('id' =>1225, 'makes_id' =>30, 'code' =>'CELICA','name' => 'Celica'),
      array('id' =>1226, 'makes_id' =>30, 'code' =>'COROL', 'name' =>'Corolla'),
      array('id' =>1227, 'makes_id' =>30, 'code' =>'CORONA', 'name' =>'Corona'),
      array('id' =>1228, 'makes_id' =>30, 'code' =>'CRESS','name' => 'Cressida'),
      array('id' =>1229, 'makes_id' =>30, 'code' =>'ECHO', 'name' =>'Echo'),
      array('id' =>1230, 'makes_id' =>30, 'code' =>'FJCRUIS', 'name' =>'FJ Cruiser'),
      array('id' =>1231, 'makes_id' =>30, 'code' =>'HIGHLANDER','name' => 'Highlander'),
      array('id' =>1232, 'makes_id' =>30, 'code' =>'LC', 'name' =>'Land Cruiser'),
      array('id' =>1233, 'makes_id' =>30, 'code' =>'MATRIX', 'name' =>'Matrix'),
      array('id' =>1234, 'makes_id' =>30, 'code' =>'MR2','name' => 'MR2'),
      array('id' =>1235, 'makes_id' =>30, 'code' =>'MR2SPYDR', 'name' =>'MR2 Spyder'),
      array('id' =>1236, 'makes_id' =>30, 'code' =>'PASEO', 'name' =>'Paseo'),
      array('id' =>1237, 'makes_id' =>30, 'code' =>'PICKUP','name' => 'Pickup'),
      array('id' =>1238, 'makes_id' =>30, 'code' =>'PREVIA','name' => 'Previa'),
      array('id' =>1239, 'makes_id' =>30,'code' => 'PRIUS','name' => 'Prius'),
      array('id' =>1240, 'makes_id' =>30,'code' => 'PRIUSC','name' => 'Prius C'),
      array('id' =>1241, 'makes_id' =>30,'code' => 'PRIUSV','name' => 'Prius V'),
      array('id' =>1242, 'makes_id' =>30,'code' => 'RAV4','name' => 'RAV4'),
      array('id' =>1243, 'makes_id' =>30,'code' => 'SEQUOIA','name' => 'Sequoia'),
      array('id' =>1244, 'makes_id' =>30,'code' => 'SIENNA','name' => 'Sienna'),
      array('id' =>1245, 'makes_id' =>30,'code' => 'SOLARA','name' => 'Solara'),
      array('id' =>1246, 'makes_id' =>30,'code' => 'STARLET','name' => 'Starlet'),
      array('id' =>1247, 'makes_id' =>30,'code' => 'SUPRA', 'name' =>'Supra'),
      array('id' =>1248, 'makes_id' =>30,'code' => 'T100', 'name' =>'T100'),
      array('id' =>1249, 'makes_id' =>30,'code' => 'TACOMA','name' => 'Tacoma'),
      array('id' =>1250, 'makes_id' =>30,'code' => 'TERCEL', 'name' =>'Tercel'),
      array('id' =>1251, 'makes_id' =>30,'code' => 'TUNDRA', 'name' =>'Tundra'),
      array('id' =>1252, 'makes_id' =>30,'code' => 'TOYVAN', 'name' =>'Van'),
      array('id' =>1253, 'makes_id' =>30, 'code' =>'VENZA', 'name' =>'Venza'),
      array('id' =>1254, 'makes_id' =>30, 'code' =>'YARIS','name' => 'Yaris / Vitz'),
      array('id' =>1255, 'makes_id' =>30, 'code' =>'TOYOTH','name' => 'Other Toyota Models'),
      array('id' =>1259, 'makes_id' =>31, 'code' =>'BEETLE','name' => 'Beetle'),
      array('id' =>1260, 'makes_id' =>31, 'code' =>'VOLKSCAB','name' => 'Cabrio'),
      array('id' =>1261, 'makes_id' =>31, 'code' =>'CAB','name' => 'Cabriolet'),
      array('id' =>1262, 'makes_id' =>31, 'code' =>'CC', 'name' =>'CC'),
      array('id' =>1263, 'makes_id' =>31, 'code' =>'CORR', 'name' =>'Corrado'),
      array('id' =>1264, 'makes_id' =>31, 'code' =>'DASHER','name' => 'Dasher'),
      array('id' =>1265, 'makes_id' =>31, 'code' =>'EOS','name' => 'Eos'),
      array('id' =>1266, 'makes_id' =>31, 'code' =>'EUROVAN','name' => 'Eurovan'),
      array('id' =>1267, 'makes_id' =>31, 'code' =>'VOLKSFOX','name' =>'Fox'),
      array('id' =>1268, 'makes_id' =>31, 'code' =>'GLI', 'name' =>'GLI'),
      array('id' =>1269, 'makes_id' =>31, 'code' =>'GOLFR','name' => 'Golf R'),
      array('id' =>1270, 'makes_id' =>31, 'code' =>'GTI', 'name' =>'GTI'),
      array('id' =>1271, 'makes_id' =>31, 'code' =>'GOLFANDRABBITMODELS','name' => 'Golf and Rabbit Models (2)'),
      array('id' =>1272, 'makes_id' =>31, 'code' =>'GOLF', 'name' =>'Golf'),
      array('id' =>1273, 'makes_id' =>31, 'code' =>'RABBIT','name' => 'Rabbit'),
      array('id' =>1274, 'makes_id' =>31, 'code' =>'JET','name' => 'Jetta'),
      array('id' =>1275, 'makes_id' =>31, 'code' =>'PASS','name' => 'Passat'),
      array('id' =>1276, 'makes_id' =>31, 'code' =>'PHAETON','name' => 'Phaeton'),
      array('id' =>1277, 'makes_id' =>31, 'code' =>'RABBITPU', 'name' =>'Pickup'),
      array('id' =>1278, 'makes_id' =>31, 'code' =>'QUAN', 'name' =>'Quantum'),
      array('id' =>1279, 'makes_id' =>31, 'code' =>'R32', 'name' =>'R32'),
      array('id' =>1280, 'makes_id' =>31, 'code' =>'ROUTAN', 'name' =>'Routan'),
      array('id' =>1281, 'makes_id' =>31, 'code' =>'SCIR', 'name' =>'Scirocco'),
      array('id' =>1282, 'makes_id' =>31, 'code' =>'TIGUAN','name' => 'Tiguan'),
      array('id' =>1283, 'makes_id' =>31, 'code' =>'TOUAREG','name' => 'Touareg'),
      array('id' =>1284, 'makes_id' =>31, 'code' =>'VANAG', 'name' =>'Vanagon'),
      array('id' =>1285, 'makes_id' =>31, 'code' =>'VWOTH','name' => 'Other Volkswagen Models'),
      array('id' =>1286, 'makes_id' =>32, 'code' =>'240', 'name' =>'240'),
      array('id' =>1287, 'makes_id' =>32, 'code' =>'260','name' => '260'),
      array('id' =>1288, 'makes_id' =>32, 'code' =>'740','name' => '740'),
      array('id' =>1289, 'makes_id' =>32, 'code' =>'760','name' => '760'),
      array('id' =>1290, 'makes_id' =>32, 'code' =>'780','name' => '780'),
      array('id' =>1291, 'makes_id' =>32, 'code' =>'850', 'name' =>'850'),
      array('id' =>1292, 'makes_id' =>32, 'code' =>'940', 'name' =>'940'),
      array('id' =>1293, 'makes_id' =>32, 'code' =>'960','name' => '960'),
      array('id' =>1294, 'makes_id' =>32, 'code' =>'C30','name' => 'C30'),
      array('id' =>1295, 'makes_id' =>32, 'code' =>'C70','name' => 'C70'),
      array('id' =>1296, 'makes_id' =>32, 'code' =>'S40', 'name' =>'S40'),
      array('id' =>1297, 'makes_id' =>32, 'code' =>'S60', 'name' =>'S60'),
      array('id' =>1298, 'makes_id' =>32, 'code' =>'S70', 'name' =>'S70'),
      array('id' =>1299, 'makes_id' =>32, 'code' =>'S80','name' => 'S80'),
      array('id' =>1300, 'makes_id' =>32, 'code' =>'S90','name' => 'S90'),
      array('id' =>1301, 'makes_id' =>32, 'code' =>'V40','name' =>'V40'),
      array('id' =>1302, 'makes_id' =>32, 'code' =>'V50', 'name' =>'V50'),
      array('id' =>1303, 'makes_id' =>32, 'code' =>'V70', 'name' =>'V70'),
      array('id' =>1304, 'makes_id' =>32, 'code' =>'V90', 'name' =>'V90'),
      array('id' =>1305, 'makes_id' =>32, 'code' =>'XC60', 'name' =>'XC60'),
      array('id' =>1306, 'makes_id' =>32, 'code' =>'XC', 'name' =>'XC70'),
      array('id' =>1307, 'makes_id' =>32, 'code' =>'XC90', 'name' =>'XC90'),
      array('id' =>1308, 'makes_id' =>32, 'code' =>'VOLOTH','name' => 'Other Volvo Models'),
      array('id' =>1315, 'makes_id' =>33, 'code' =>'LIESSEII','name' => 'LIESSE II'),
      array('id' =>1316, 'makes_id' =>28, 'code' =>'Escudo','name' => 'Escudo'),
      array('id' =>1317, 'makes_id' =>9, 'code' =>'Vezel','name' => 'HR-V / Vezel'),
      array('id' =>1318, 'makes_id' =>24, 'code' =>'208','name' => '208'),
      array('id' =>1319, 'makes_id' =>22, 'code' =>'Shogun','name' => 'Shogun'),
      array('id' =>1320, 'makes_id' =>22, 'code' =>'Pajero','name' => 'Pajero'),
      array('id' =>1321, 'makes_id' =>17, 'code' =>'ROV','name' => 'Range Rover Velar'),
      array('id' =>1322, 'makes_id' =>17, 'code' =>'ROV','name' => 'Range Rover Vogue'),
      array('id' =>1323, 'makes_id' =>17, 'code' =>'ROV','name' => 'Range Rover Vogue Autobiography'),
      array('id' =>1324, 'makes_id' =>30, 'code' =>'Vanguard','name' => 'Vanguard'),
      array('id' =>1325, 'makes_id' =>23, 'code' =>'XTRAIL','name' => 'Xtrail'),
      array('id' =>1326, 'makes_id' =>23, 'code' =>'SKY','name' => 'Skyline'),
      array('id' =>1327, 'makes_id' =>30, 'code' =>'ractis','name' => 'Ractis'),
      array('id' =>1328, 'makes_id' =>30, 'code' =>'Noah','name' => 'Noah'),
      array('id' =>1329, 'makes_id' =>30, 'code' =>'Coaster','name' => 'Coaster'),
      array('id' =>1330, 'makes_id' =>30, 'code' =>'Fortuner','name' => 'Fortuner'),
      array('id' =>1331, 'makes_id' =>30, 'code' =>'Harrier','name' => 'Harrier'),
      array('id' =>1332, 'makes_id' =>30, 'code' =>'TX','name' => 'Land Cruiser Prado TX'),
      array('id' =>1333, 'makes_id' =>30, 'code' =>'TXL','name' => 'Land Cruiser Prado TXL'),
      array('id' =>1334, 'makes_id' =>30, 'code' =>'TZG','name' => 'Land Cruiser Prado TZG'),
      array('id' =>1335, 'makes_id' =>30, 'code' =>'VX','name' => 'Land Cruiser Prado VX'),
      array('id' =>1336, 'makes_id' =>30, 'code' =>'VXL','name' => 'Land Cruiser Prado VXL'),
      array('id' =>1337, 'makes_id' =>30, 'code' =>'SAHARA','name' => 'Land Cruiser Sahara'),
      array('id' =>1338, 'makes_id' =>30, 'code' =>'ZX','name' => 'Land Cruiser ZX'),
      array('id' =>1339, 'makes_id' =>30, 'code' =>'VX','name' => 'Land CruiserVX'),
      array('id' =>1340, 'makes_id' =>30, 'code' =>'MARKX','name' => 'Mark X'),
      array('id' =>1341, 'makes_id' =>30, 'code' =>'PROBOX','name' => 'Probox'),
      array('id' =>1342, 'makes_id' =>30, 'code' =>'Succeed','name' => 'Succeed'),
      array('id' =>1343, 'makes_id' =>30, 'code' =>'HiAce','name' => 'HiAce'),
      array('id' =>1344, 'makes_id' =>30, 'code' =>'HiAce','name' => 'HiAce Commuter'),
      array('id' =>1345, 'makes_id' =>30, 'code' =>'Allion','name' => 'Allion'),
      array('id' =>1346, 'makes_id' =>30, 'code' =>'Hilux','name' => 'Hilux'),
      array('id' =>1347, 'makes_id' =>30, 'code' =>'Hilux','name' => 'Hilux Double Cabin'),
      array('id' =>1348, 'makes_id' =>22, 'code' =>'Rosa','name' => 'Rosa'),
      array('id' =>1349, 'makes_id' =>22, 'code' =>'Delica','name' => 'Delica'),
      array('id' =>1350, 'makes_id' =>3, 'code' =>'520i','name' => '520i'),
      array('id' =>1351, 'makes_id' =>20, 'code' =>'Bongo','name' => 'Bongo'),
      array('id' =>1352, 'makes_id' =>21, 'code' =>'CClass','name' => 'C180'),
      array('id' =>1353, 'makes_id' =>21, 'code' =>'CClass','name' => 'C200'),
      array('id' =>1354, 'makes_id' =>21, 'code' =>'CLS','name' => 'CLS350'),
      array('id' =>1355, 'makes_id' =>21, 'code' =>'ML270','name' => 'ML270'),
      array('id' =>1356, 'makes_id' =>21, 'code' =>'E250','name' => 'E250'),
      array('id' =>1357, 'makes_id' =>21, 'code' =>'GL500','name' => 'GL500'),
      array('id' =>1358, 'makes_id' =>13, 'code' =>'ELF','name' => 'ELF'),
      array('id' =>1359, 'makes_id' =>23, 'code' =>'NV200','name' => 'NV200'),
      array('id' =>1360, 'makes_id' =>23, 'code' =>'Caravan','name' => 'Caravan'),
      array('id' =>1361, 'makes_id' =>23, 'code' =>'NV350','name' => 'NV350'),
      array('id' =>1362, 'makes_id' =>23, 'code' =>'Navara','name' => 'Navara'),
      array('id' =>1363, 'makes_id' =>23, 'code' =>'NP300','name' => 'NP300'),
      array('id' =>1364, 'makes_id' =>23, 'code' =>'Note','name' => 'Note'),
      array('id' =>1365, 'makes_id' =>17, 'code' =>'ROV','name' => 'Range Rover Vogue SE'),
    );
    DB::table('models')->insert($models1);
    }
}
